# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: E9hsKWjQPJEbmVX9GcFh

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 6685:6685
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: E9hsKWjQPJEbmVX9GcFh
